version: '2'
services:
  mynode: 
    build: .
    image: theprotroop-my-node-app
    container_name: theprotroop-my-node-app
    restart: unless-stopped
    ports:
    - "3000:3000"
    #volumes:
      #- /opt/good:/usr/src/app/files
